aggregation_method: median
attack: signflip
cgc_method: by-layer
comm_range:
  v2rsu: 100
dataset: mnist
neural_network:
  batch_size: 100
  epoch: 100
  learning_rate: 0.0005
num_faulty_grads: 5
num_training_data: 50000
num_val_loss: 5000
seed: 0
simulation:
  FCD_FILE: ../osm_boston_common/osm_fcd.xml
  NET_FILE: ../osm_boston_common/osm.net.xml
  ROU_FILE: ../osm_boston_common/osm.passenger.trips.xml
  maximum_rsu_accumulative_gradients: 10
  num_rsu: 8
